#!/usr/bin/env python3
"""Spread the kernel tile variants of the low-precision forward families over separate translation units.

For every per-type unit src/<family>_iK.cu (one explicit instantiation of the family's dispatcher for a type pair T, TO)
this writes src/<family>_iK<tag>.cu per launcher with the explicit instantiations of all the launcher's tile variants for
that type pair, and adds matching `extern template` declarations to src/<family>_iK.cu so the dispatcher unit does not
compile them again. Units of verification types (bf16 / fp32) stay under #ifdef UFSM_ALL_TYPES (make VERIFY=1).
Re-run after changing a launcher's variant list or signature: tools/gen_lp_launch.py"""
import glob, re

SIG = '(dim3 grid, const void *x, shape5 xs, const uint8_t *wq, const uint8_t *ws, const float *b, int cout, void *y, int Cop, %sgnp_t gp, double *osum, int Go, split_t sp)'
FAMILIES = {
    'lp_f8fwd': [   # (tag, launcher, variants, signature, also for mixed T != TO)
        ('g', 'launch_f8g', [(1, 2), (1, 4), (2, 2), (2, 4), (4, 2)], SIG % 'int Cip, ', False),
        ('p', 'launch_f8p', [(1, 2), (1, 4), (2, 2), (2, 4), (3, 2), (3, 4), (4, 2)], SIG % '', False),
        ('s', 'launch_f8s', [(m, c) for m in (1, 2, 4) for c in (4, 8, 16)], SIG % '', True),
    ],
    'lp_f4fwd': [
        ('g', 'launch_f4', [(1, 2), (1, 4), (2, 2), (2, 4), (4, 2)], SIG % 'int Cip, ', True),
        ('p', 'launch_f4p', [(1, 2), (1, 4), (2, 2), (2, 4), (3, 2), (3, 4), (4, 2)], SIG % '', True),
    ],
}
MARK = '/* tile variants instantiated in the %s_i%d<tag>.cu units (tools/gen_lp_launch.py) */'


def verify(types): return re.search(r'\b(bf16|float)\b', types) is not None


for fam, launchers in FAMILIES.items():
    for f in sorted(glob.glob('src/%s_i*.cu' % fam)):
        m = re.match(r'src/%s_i(\d+)\.cu$' % fam, f)
        if not m: continue
        k = int(m.group(1)); text = open(f).read()
        tm = re.search(r'^template void \w+<([^>]*)>', text, re.M)
        ts = [t.strip() for t in tm.group(1).split(',')]
        if len(ts) == 1: ts = ts * 2
        T, TO = ts; mixed = T != TO; vt = verify(tm.group(1))
        ext = []
        for tag, name, variants, sig, for_mixed in launchers:
            if mixed and not for_mixed: continue
            lines = ['template void %s<%d, %d, %s, %s>%s;' % (name, a, c, T, TO, sig) for a, c in variants]
            body = '/* %s tile variants for %s, %s (generated by tools/gen_lp_launch.py) */\n#include "%s.cuh"\n' % (name, T, TO, fam)
            body += ('#ifdef UFSM_ALL_TYPES\n' + '\n'.join(lines) + '\n#endif\n') if vt else '\n'.join(lines) + '\n'
            open('src/%s_i%d%s.cu' % (fam, k, tag), 'w').write(body)
            ext += ['extern ' + l for l in lines]
        text = re.sub(r'\n' + re.escape(MARK % (fam, k)).replace('<tag>', '<tag>') + r'\n(extern template [^\n]*\n)*', '\n', text)
        i = text.index('\n', text.index('#include')) + 1
        text = text[:i] + MARK % (fam, k) + '\n' + '\n'.join(ext) + '\n' + text[i:]
        open(f, 'w').write(text)
        print(f, T, TO, len(ext), 'variants')
