/* launch_f4 tile variants for mx4_t, float (generated by tools/gen_lp_launch.py) */
#include "lp_f4fwd.cuh"
#ifdef UFSM_ALL_TYPES
template void launch_f4<1, 2, mx4_t, float>(dim3 grid, const void *x, shape5 xs, const uint8_t *wq, const uint8_t *ws, const float *b, int cout, void *y, int Cop, int Cip, gnp_t gp, double *osum, int Go, split_t sp);
template void launch_f4<1, 4, mx4_t, float>(dim3 grid, const void *x, shape5 xs, const uint8_t *wq, const uint8_t *ws, const float *b, int cout, void *y, int Cop, int Cip, gnp_t gp, double *osum, int Go, split_t sp);
template void launch_f4<2, 2, mx4_t, float>(dim3 grid, const void *x, shape5 xs, const uint8_t *wq, const uint8_t *ws, const float *b, int cout, void *y, int Cop, int Cip, gnp_t gp, double *osum, int Go, split_t sp);
template void launch_f4<2, 4, mx4_t, float>(dim3 grid, const void *x, shape5 xs, const uint8_t *wq, const uint8_t *ws, const float *b, int cout, void *y, int Cop, int Cip, gnp_t gp, double *osum, int Go, split_t sp);
template void launch_f4<4, 2, mx4_t, float>(dim3 grid, const void *x, shape5 xs, const uint8_t *wq, const uint8_t *ws, const float *b, int cout, void *y, int Cop, int Cip, gnp_t gp, double *osum, int Go, split_t sp);
#endif
